const LISTSPACE = {
    FETCH_SUCCESS: 'LISTSPACE_FETCH_SUCCESS',
    SEARCH_SUCCESS: 'LISTSPACE_SEARCH_SUCCESS',
    FETCH_FAILED: 'LISTSPACE_FETCH_FAILED',
}

const DETAILSPACE = {
    FETCH_SUCCESS: 'DETAILSPACE_FETCH_SUCCESS',
    FETCH_FAILED: 'DETAILSPACE_FETCH_FAILED',
}

export { LISTSPACE, DETAILSPACE };